server:
  port: 8082

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/opentask
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      
jwt.signing.key.secret: mySecret
jwt.get.token.uri: /authenticate
jwt.refresh.token.uri: /refresh
jwt.http.request.header: Authorization
jwt.token.expiration.in.seconds: 604800