server:
  port: 8082

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/opentask
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update